### ISSUE TITLE
Gallery: Selecting a photo from gallery or "view photos" option crashes the app.

### ISSUE THREAD

**Issue by vppatel111** [CMPUT301F18T24/Mark-Me#99]
Here's a short stack trace, the bitmap is getting recycled somewhere.
                  java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f2964c6
                      at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55)
                      at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
                      at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
                      at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
                      at android.widget.ImageView.onDraw(ImageView.java:1367)

**Comment by dorsMaster** [comment]
fixed.
